# Generated by Django 5.1.1 on 2025-02-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_image_keranjang_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AlterField(
            model_name='keranjang',
            name='image',
            field=models.CharField(blank=True),
        ),
    ]
